# Generated by Django 3.2.7 on 2021-09-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('datetime', models.DateTimeField(blank=True)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
